### PR TITLE
Enable SIMD

### PR DESCRIPTION
**Pull request by andreas**
This PR enables compilation with SIMD WASM instructions. I decided on the `emcc` flags by comparing the intrinsic headers [used by CRoaring](https://github.com/RoaringBitmap/CRoaring/blob/master/include/roaring/portability.h#L127-L134) with the flags from the [emscripten simd documentation](https://emscripten.org/docs/porting/simd.html).

Compiling with SIMD enabled means the generated WASM can only run on targets with SIMD support though. According to [webassembly.org](https://webassembly.org/roadmap/), SIMD is supported is recent modern browsers and since Node v16.4 (see below). Alternatively we need to create two WASM artifacts (with/without SIMD) and [select at runtime](https://v8.dev/features/simd#enabling-simd-support) -- that would create more overhead both in build size and code complexity though.

Roadmap_-_WebAssembly

To verify the performance impact, the benchmark test could benefit from being improved. I didn't include that for now though.

### CODE REVIEW

**Comment by SalvatorePreviti** [comment]
Sounds good! If the need arises for browser or CPUs that do not support those flags we can improve the compilation and build 2 wasm (and 2 browsers version). I will in any case try to improve the build step to produce a faster and more portable .js file from emcc - not worried of complexity, but as you say, if is well supported, I don't see a reason to add complexity

**Comment by SalvatorePreviti** [comment]
Ok I am approving this, but I noticed that however this does not leverage the custom SSE code and the intrinsics supported by emscripten in CRoaring - they seems to be enabled only when compiling on an X64 processor so if __x86_64__ is defined, that results in a CROARING_IS_X64 is 1 - but forcing CROARING_IS_X64 to be 1 seems also to want to use AVX2 instructions that are not supported by emscripten so I get compilation error - it seems that croaring assumes AVX2 to be present if CROARING_IS_X64 - if it worth to try to have full simd support (SSE4.2) it worth more investigation and raising in case the issue with CRoaring authors and Lemire

**Comment by SalvatorePreviti** [comment]
As a side note, adding this in packages/roaring-wasm-src/cpp/global.h will indeed try to compile with SSE4.2 instructions, but fails because this assumes also AVX2 instructions.

```#include <xmmintrin.h>
#include <emmintrin.h>
#include <smmintrin.h>
#include <immintrin.h>
#include <nmmintrin.h>

#define CROARING_CLANG_VISUAL_STUDIO 0
#define CROARING_IS_X64 1
#define CROARING_COMPILER_SUPPORTS_AVX512 0```

**Review by SalvatorePreviti — APPROVED** [review]

**Comment by lemire** [comment]
> fails because this assumes also AVX2 instructions

In CRoaring, we have three kinds of optimized functions: AVX2, AVX-512 and NEON (ARM64). If you have an x64 processor, we attempt to compute both AVX2, AVX-512, as well as the standard (fallback) routines. If you compile for x64, you already get SSE2 autovectorization in the fallback routines, so we don't try to do that manually. It is only worth doing AVX2 and AVX-512 manually.

So if you are not enabling AVX2 or AVX-512 or NEON, then you do not get any custom SIMD support, just the compiler autovectorization.

> will indeed try to compile with SSE4.2 instructions, but fails because this assumes also AVX2 instructions.

We assume that current x64 compilers supporting SSE4.2 instructions ought to be able to compile AVX2 instructions as well. If that's not the case for you, you can pass the compile-time macro `ROARING_DISABLE_AVX=1`. It will disable any kind of AVX code even if it would otherwise be supported. Doing so is likely to disable any custom SIMD optimization in CRoaring.

**Comment by SalvatorePreviti** [comment]
Thank you!

Now, at the moment the added compile arguments in this pull request might not have effect because CRoaring does not recognise the X64 architecture so it does not use any specific SIMD intrinsics, @andreas are you sure they have an effect in the compiled code?

So, as reported, emscripten has its own WASM specific header file wasm_simd128.h that exposes WASM intrinsics.
Emscripten offers also a compatibility layer, most of NEON or most AVX 128 bit instructions are supported - however some instructions are not ported and others are emulated, they can be slower! Benchmarking here would be needed.

It seems that also disabling AVX2 with ROARING_DISABLE_AVX=1 I get compilation error on some 256 bit wide types and instructions in popcount256 in bitset_util.h, not sure exactly why...

However CRoaring uses also other instructions not currently ported or supported by emscripten - in particular, _mm_cmpestrm. Emscripten doc says "The SSE4.2 functions that deal with string comparisons and CRC calculations are not available". 

I tried to enable NEON instead of X64, but it does not work either, seems a bug on emscripten? "arm_neon.h:31018:7: error: first argument to __builtin_convertvector must be a vector"


In general, I am not sure if trying to use WASM SIMD or AVX or NEON instructions is feasible right now.

source: https://emscripten.org/docs/porting/simd.html#compiling-simd-code-targeting-arm-neon-instruction-set

**Comment by lemire** [comment]
@easyaspi314 Can you help?

**Comment by easyaspi314** [comment]
I don't seem to get any errors compiling for NEON. And NEON is almost always better for WASM128 as long as half vectors are avoided.

**Comment by easyaspi314** [comment]
Ah, yeah this is a bug in SIMDe. It just didn't show up at first because I missed the USENEON flag.

I see the problem, as the `float16x8_t` doesn't use a vector type if the ABI doesn't support it properly.

**Comment by SalvatorePreviti** [comment]
So the answer would be raise an issue with emscripten if still there isn't one and wait a new release then we can enable NEON instead of x64 :) sounds great

**Comment by easyaspi314** [comment]
The define hack works as well. 

```javascript
    emccFlags.push("-msimd128");
    emccFlags.push("-mfpu=neon");
    emccFlags.push("-DSIMDE_NO_CONVERT_VECTOR");
```

**Comment by SalvatorePreviti** [comment]
I get a few warnings, will investigate further and will check emcc if they plan to update this header soon
image

**Comment by andreas** [comment]
> @andreas are you sure they have an effect in the compiled code?

When compiling with the added flags, I got runtime errors when executing the WASM with v8 6.4.388.40 (via [plv8](https://github.com/plv8/plv8) v2.3.12) and Node v14, because neither support SIMD. So I figured that the compiled WASM _did_ include SIMD instructions. I didn't try confirming by inspecting the actual instructions or through benchmarks though, so it could have been a premature conclusion.

I appreciate all the effort going into this conversation, so thanks all 🙏

**Comment by SalvatorePreviti** [comment]
Yes @andreas my new understanding is indeed that the flag `-msimd128` adds autovectorization so add some automatic optimization to the existing C code, but the other flags for X64 are currently unused and have no effect - to leverage the custom hand made SIMD code written in CRoaring the best solution as proposed by easyaspi314 is to use NEON instructions instead so we leverage the portability layer that converts those NEON instruction to WASM SIMD with [SIMDE](https://github.com/simd-everywhere/simde)

So you are right that SIMD instructions are emitted, but to fully leverage CRoaring SIMD implementation we will need NEON instructions enabled, and I will raise another PR for that.

Thanks a lot for your work on this and for starting this! Super appreciated!

**Comment by SalvatorePreviti** [comment]
Created a GitHub project - https://github.com/users/SalvatorePreviti/projects/1 feel free to use it :)
